spring.application.name=back
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/medilabo
spring.datasource.username=medilabo
spring.datasource.password=medilabopass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
